default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST", "db") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: Budgy_development

test:
  <<: *default
  database: Budgy_test

production:
  <<: *default
  database: Budgy_production
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
